# tasks file for ssh-server
---
- name: Check for local key and generate if needed
  local_action: >
    command  ssh-keygen -t rsa -f "{{ ssh_server_local_key | default('~/.ssh/id_rsa') }}" -N ''
  args:
    creates: "{{ ssh_server_local_key | default('~/.ssh/id_rsa') }}"
  register: check_local_key
  changed_when: "'Generating public/private rsa key pair.' \
                in check_local_key.stdout"
  tags:
    - ssh-server
    - ssh-server-check-local-key


- name: Authorize key for local user
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', ssh_server_local_key | default('~/.ssh/id_rsa') + '.pub') }}"
  tags:
    - ssh-server
    - ssh-server-authorized-key


- name: Generate remote key
  command: ssh-keygen -t rsa -f "{{ ssh_server_remote_key }}" -N ''
  args:
    creates: "{{ ssh_server_remote_key }}"
  register: check_remote_key
  changed_when: "'Generating public/private rsa key pair.' \
                in check_remote_key.stdout"
  when: ssh_server_remote_key is defined and ssh_server_remote_key 
  tags:
    - ssh-server
    - ssh-server-check-remote-key


- name: Install/update ssh server
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ ssh_server_install | default('openssh-server') }}"
  become: true
  tags:
    - ssh-server
    - ssh-server-install


- name: Update configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: 'sshd -T -f %s'
  notify: restart ssh
  become: true
  tags:
    - ssh-server
    - ssh-server-config


- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_server_allow_groups + ssh_server_deny_groups | default([]) }}"
  become: yes
  tags:
    - system
    - users
    - users-create


- name: Start and enable ssh service
  service:
    name: ssh
    state: started
    enabled: true
  become: true
  tags:
    - ssh-server
    - ssh-server-start-enable-service


# vim:ft=ansible :
